---
- name: This is used to deploy the latest version of Yazz publicly
  hosts: webservers
  vars:
    PROCESS: node
  tasks:

    - name: Kill running processes
      shell: "killall node"
      ignore_errors: yes

    - name: Kill running processes part 2
      shell: "killall yazz_app_loop.s"
      ignore_errors: yes


    - command: git reset --hard origin/master
      args:
        chdir: /root/visifile


    - name: install the latest version of Yazz
      git:
        repo: 'https://github.com/yazz/yazz.git'
        dest: /root/visifile
        version: "{{ sha }}"

    - name: build docs
      shell:
        cmd: asciidoc   -d book   main.adoc
      args:
        chdir: /root/visifile/public/visifile/docs/book/



    - name: Start Yazz
      shell:
        cmd: chmod +x yazz_app_loop.sh; ./yazz_app_loop.sh  {{ ssl_public_key }}   {{ ssl_private_key }}   {{ use_host }}  {{ ssl_cacert1 }}  {{ ssl_cacert2 }}  {{ ssl_cacert3 }} &
      async: 10
      poll: 0
      args:
        chdir: /root/visifile/
